In [1]:
import pandas as pd

In [2]:

data = pd.read_csv("data_to_use.csv")
data.head(2)



a0          a1         a2         a3         a4        a5  \
0 -402.785676   92.733659  19.382511 -13.098001  -5.988058  2.662205   
1 -366.470332  126.436917  31.174048 -23.376111 -13.181028  0.684520   

          a6         a7         a8        a9    ...            d4         d5  \
0 -15.008122  -7.915385  -9.553994 -6.019916    ...     19.884858  17.577290   
1 -27.094633 -19.214334 -22.217589 -9.954311    ...     22.688885  20.651954   

          d6        d7        e1        e2        e3        e4        e5  \
0  30.952526 -0.008063 -0.006023 -0.004361 -0.060430 -0.008714  0.000939   
1  32.138705 -0.008300 -0.008378 -0.038486 -0.039242 -0.005562  0.005952   

      label  
0  dog_bark  
1  dog_bark  

[2 rows x 194 columns]

In [3]:
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder
labelEncoder_for_catagories=LabelEncoder()
data['label']=labelEncoder_for_catagories.fit_transform(data['label'])

In [5]:
data

a0          a1         a2         a3         a4         a5  \
0    -402.785676   92.733659  19.382511 -13.098001  -5.988058   2.662205   
1    -366.470332  126.436917  31.174048 -23.376111 -13.181028   0.684520   
2    -421.527284   69.038612  11.259902  -1.287742   2.871705   2.559122   
3    -253.197551   99.437913 -42.032761 -13.843607  -9.055074  -6.101550   
4    -383.810140  128.451556  29.313243  18.846984  -6.675448   0.989596   
5    -392.419765  100.693821  38.338770  31.595787   9.919755  12.658040   
6    -373.947087  105.279395  23.840941  21.311101   4.102846   9.905532   
7    -391.955112   86.237595  18.303868  22.618829   6.491297  11.243356   
8    -396.395847   81.971960  16.738000  22.344192   5.956769  12.111015   
9    -172.124865  109.293454 -41.404116   3.420816 -12.714169   3.016030   
10   -183.645313  108.943015 -45.983388  -4.863444 -12.974643  -2.940457   
11   -185.335011  117.889661 -30.153260   0.557286  -2.289074  -2.037386   
12   -193.833039  119.784178 -41.914353  -3.742694  -6.659315  -3.556513   
13   -179.156552  101.783505 -37.419370   6.599988  -8.065268  -1.209287   
14   -175.593082  110.059133 -39.250623   6.041333  -9.438048   0.183312   
15   -206.187582  116.302625 -35.980928   5.781494  -2.752721   3.389666   
16   -232.865278  126.213375 -32.904140   2.734920  -3.975627  -4.907982   
17    -46.277045   79.954965 -48.603514   9.624830 -15.820139  17.731534   
18    -62.296151   93.509408 -59.751621   5.927392 -17.117130  19.007796   
19    -87.475749  102.345833 -65.628293   4.194328 -13.586373  22.395917   
20   -104.717850  105.257545 -63.735235   5.870468 -17.817818  21.392198   
21   -103.820389   92.240061 -43.253119  32.481827 -15.403102   5.065240   
22    -86.036649  100.797856 -29.869050  23.444289 -12.112990   6.933221   
23    -93.383668  103.012006 -39.849587  24.822385 -21.362720   3.705882   
24   -103.029502  101.465269 -34.337005  31.517362 -17.250251   3.124396   
25   -106.005407  104.105857 -30.097003  33.148328 -10.611698   7.546410   
26   -107.487661  103.009811 -26.835916  26.680504 -15.167398   9.689350   
27   -103.921302   90.244314 -39.394092  20.714833 -23.852438   9.870833   
28   -375.192239   42.285324 -54.171084 -21.446088 -35.956912 -17.180587   
29   -254.873934   32.753594 -85.887930 -31.180715 -54.670302 -17.981732   
...          ...         ...        ...        ...        ...        ...   
5724 -158.835903  101.417475 -35.645908  -2.352159   6.008842  13.883534   
5725 -148.004684  100.241257 -40.437831  -0.264024   6.112576  13.534919   
5726 -177.202006   59.522144 -15.416924 -16.520592 -36.546494  25.225346   
5727  -80.165868   46.835388  -4.020974 -25.929416  -8.773620 -23.280867   
5728  -95.461380   49.716452  -5.663332 -21.119976  -6.945285 -22.082673   
5729 -118.115422   40.968647 -13.799229 -13.179218  -3.711657 -20.236991   
5730 -137.111312   47.793753 -23.600762 -11.612398  -2.804642 -17.408497   
5731 -182.704225   29.300228 -40.958192  -6.008491  -3.198512 -14.153943   
5732 -141.762910   31.961169 -29.819128 -14.608500  -7.038758 -17.610210   
5733  -78.167087   59.194762  -5.014760 -24.207852 -10.099997 -22.508147   
5734 -183.203294   41.437286  -3.920621 -12.617137  -5.340137 -14.094930   
5735 -169.267377   31.118522  -0.664402 -13.735898  -1.218001 -11.813743   
5736 -131.986011   30.220017   5.558954 -23.942328  -2.857389 -16.558838   
5737 -168.306651   29.394040  -2.194510 -16.509020  -2.134601 -13.312587   
5738 -129.151127   33.347721 -20.984498 -15.126296  -3.578497 -17.224785   
5739 -109.201629   30.397500   0.919569 -25.886556 -12.026766 -23.565092   
5740 -134.891316   35.393983 -19.194447 -10.712572  -3.515702 -18.048428   
5741 -147.886404   33.827644 -22.687833  -8.146015   0.198728 -15.974909   
5742 -100.132382   32.775536   0.490950 -19.887396  -3.935636 -22.968618   
5743 -121.568129   35.154099 -12.927746 -13.120072  -3.643837 -19.527445   
5744 -124.829818   32.910813 -13.443976 -13.363981  -2.198489 

In [6]:
import seaborn as sns
data.shape

(5754, 194)

In [7]:
features = data[0:5754]

In [8]:
features = features.drop(['label'],axis=1)

In [9]:
features.shape
features = features.values

In [10]:
labels = data.loc[:,['label']].values

In [11]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import AdaBoostClassifier
#clf = DecisionTreeClassifier(random_state=0)

In [20]:
clf = GradientBoostingClassifier(n_estimators=1000, learning_rate=1.0)

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
X_train, X_test, y_train, y_test = train_test_split(features, labels, test_size=0.3)

In [23]:
clf.fit(X_train,y_train)

F:\nff\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=1.0, loss='deviance', max_depth=3,
              max_features=None, max_leaf_nodes=None,
              min_impurity_decrease=0.0, min_impurity_split=None,
              min_samples_leaf=1, min_samples_split=2,
              min_weight_fraction_leaf=0.0, n_estimators=1000,
              presort='auto', random_state=None, subsample=1.0, verbose=0,
              warm_start=False)

In [24]:
pred=clf.predict(X_test)

In [25]:
clf.score(X_test,y_test)

0.8187608569774175

In [26]:
from sklearn.metrics import classification_report

In [27]:
print(classification_report(pred,y_test))

             precision    recall  f1-score   support

          0       0.91      0.89      0.90       167
          1       0.74      0.92      0.82        85
          2       0.82      0.80      0.81       171
          3       0.78      0.84      0.81       223
          4       0.81      0.77      0.79       241
          5       0.77      0.79      0.78       178
          6       0.79      0.94      0.86        66
          7       0.87      0.87      0.87       154
          8       0.88      0.88      0.88       215
          9       0.80      0.68      0.74       227

avg / total       0.82      0.82      0.82      1727



In [28]:
 from sklearn.metrics import confusion_matrix

In [30]:
confusion_matrix(y_test, pred)

array([[149,   0,   3,   0,   4,   4,   0,   0,   0,   4],
       [  1,  78,   1,   3,   2,   3,   0,   3,   1,  13],
       [  1,   0, 136,   5,   4,   1,   0,   1,   6,  12],
       [  1,   5,  15, 187,   7,   4,   0,   0,   5,  16],
       [  0,   1,   3,   4, 185,  16,   0,   6,   4,  10],
       [  6,   0,   1,   1,  18, 140,   2,   2,   3,  10],
       [  0,   0,   3,   5,   2,   0,  62,   5,   0,   1],
       [  1,   1,   0,   2,   6,   6,   1, 134,   0,   3],
       [  1,   0,   4,  13,   4,   1,   0,   0, 189,   4],
       [  7,   0,   5,   3,   9,   3,   1,   3,   7, 154]], dtype=int64)

In [31]:
import pickle
s = pickle.dumps(clf)

In [3]:
from joblib import dump, load
dump(clf, 'GBClassifier.joblib') 

NameError: name 'clf' is not defined

In [4]:
clf = load('GBClassifier.joblib') 

In [35]:
clf.predict(X_test)

array([6, 4, 7, ..., 5, 5, 5], dtype=int64)

In [36]:
clf.score(X_test,y_test)

0.8187608569774175

In [18]:
import librosa
import soundfile as sf


In [24]:
read= sf.read("a3.wav")

In [25]:
def extract_feature(file_name: str) -> tuple:
    """
    Extracts 193 chromatographic features from sound file. 
    including: MFCC's, Chroma_StFt, Melspectrogram, Spectral Contrast, and Tonnetz
    NOTE: this extraction technique changes the time series nature of the data
    """
    X, sample_rate = librosa.load(file_name)
    stft = np.abs(librosa.stft(X))
    mfccs = np.mean(librosa.feature.mfcc(y=X, sr=sample_rate, n_mfcc=40).T,axis=0)
    chroma = np.mean(librosa.feature.chroma_stft(S=stft, sr=sample_rate).T,axis=0)
    mel = np.mean(librosa.feature.melspectrogram(X, sr=sample_rate).T,axis=0)
    contrast = np.mean(librosa.feature.spectral_contrast(S=stft, sr=sample_rate).T,axis=0)
    tonnetz = np.mean(librosa.feature.tonnetz(y=librosa.effects.harmonic(X), sr=sample_rate).T,axis=0)
    return mfccs,chroma,mel,contrast,tonnetz

In [26]:
import numpy as np
mfccs,chroma,mel,contrast,tonnetz = extract_feature("a3.wav")
features = np.empty((0,193))
ext_features = np.hstack([mfccs,chroma,mel,contrast,tonnetz])
features = np.vstack([features,ext_features])
features= pd.DataFrame(features)

In [27]:
clf.predict(features)

array([6], dtype=int64)

In [48]:
%whos

Variable                      Type                          Data/Info
---------------------------------------------------------------------
AdaBoostClassifier            ABCMeta                       <class 'sklearn.ensemble.<...>ting.AdaBoostClassifier'>
DecisionTreeClassifier        ABCMeta                       <class 'sklearn.tree.tree<...>.DecisionTreeClassifier'>
GradientBoostingClassifier    ABCMeta                       <class 'sklearn.ensemble.<...>dientBoostingClassifier'>
LabelEncoder                  type                          <class 'sklearn.preproces<...>sing.label.LabelEncoder'>
X_test                        ndarray                       1727x193: 333311 elems, type `float64`, 2666488 bytes (2.5429611206054688 Mb)
X_train                       ndarray                       4027x193: 777211 elems, type `float64`, 6217688 bytes (5.929649353027344 Mb)
chroma                        ndarray                       12: 12 elems, type `float64`, 96 bytes
classification_report 